services :
  pg:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER : "gleb"
      POSTGRES_PASSWORD : "123"
      POSTGRES_DB : "weather"
    ports:
      - "54321:5432"
